### ISSUE TITLE
TAKIM OLUŞTURULMASI / ÜYELİK İŞLEMLERİ

### ISSUE THREAD

**Issue by zsgoksu** [zsgoksu/rakibinisensec#1]
1-) Takımların sisteme kayıt olma süreci ve takım lokasyonları ait story ve kullanıcı kabul testi.

**Comment by umutbarangok** [comment]
Deneme

**Comment by bahadirhalil** [comment]
User Story'ler boyle olmaması lazım değil mi? Slaytlara bir göz atın isterseniz..
