### ISSUE TITLE
UserStory and Testing

### ISSUE THREAD

**Issue by zsgoksu** [zsgoksu/rakibinisensec#6]
> ## User Story

## 1-)Üyelik işlemleri
Sisteme kayıt olmak isteyen kullanıcı olarak takım oluşturup rakip seçebilmem için sisteme kayıt olma panelinden ;

a-)Oluşturmak istediğim takımın adını belirleyebilmeyim.
b-)Takımda bulunan kişi sayısı belirleyebilmeliyim.
c-)Belirlediğim kişilerin bilgilerini ekleyebilmeliyim.
d-)Takımın bulunduğu konum hakkındaki bilgileri ekleyebilmeyim.

## 2-)Rakip Arama işlemleri
Takımların rakip arayabilmesi için öncelikle kayıt olmaları gerekmektedir. Üyelik işlemlerinden sonra rakip arayabilirler. Üye girişi yapan takımlar eşleşmeler menüsüne tıklayarak arama tercihlerinden bir veya bir kaçını seçerek;

- Konuma göre maç araması yapabilirim.
- Zamana göre maç araması yapabilirim.
- Takım değerlendirmelerine göre maç araması yapabilirim.

## 3-)Yeni Karşılaşma Oluşturma ve Saha Seçimi
Saha seçim işlemi yeni maç talebi ile birlikte yapılabilir. Daha önceden sistemde kayıtlı olan sahalardan birini takım tercih edebilir.

- Takım olarak yeni bir maç oluşturarak rakiplerimi bekleyebilirim.
- Takım olarak saha özelliklerine göre oynamak istediğim sahayı seçebilirim.
- Saha ücretlerini görerek aralarında tercih yapabilirim.
- Zamanı takım olarak belirleyebilirim.

## 4-)Eşleşme Sonuçları
Daha önceden karşılaştırma oluşturan üye'ye bildirim yoluyla başka bir rakiple eşleştiği duyrulur. 
Eğer rakibini uygun görürse onaylar.

- Maç isteklerimi görüntüleyebilirim.
- Takım olarak karşılabilceğimiz takımlar içinden tercih yapabilirim.
- Kriterlerini beğenmediğim takımları eleyebilirim.

## 5-)Rakiplerin Yorumu
Opsiyonel bir tercih maç tarihinden sonra isteğe bağlı sistemde karşılaşma yapılan takım adına geri dönüş yapar. Yorum yazmak yada puanlama yapmak isteğe bağlıdır.

- Son karşılaştığım takım hakkında yorum yapabilir onları puanlama ile değerlendirebilirim.

> ## Testing

## 1-)Üyelik işlemleri
a-)
b-)
c-)
d-)
e-)
## 2-)Rakip Arama işlemleri

- Belirtilen kriterlerde arama yaptım;
      - İstediğim özellikte takım buldum.
      - İstediğim özellikte takım bulamadım.
          - Kriterleri değiştirdim tekrar arama yaptım.

## 3-)Yeni Karşılaşma Oluşturma ve Saha Seçimi

- Yeni bir karşılaştırma oluşturdum;
      - Zaman aralığı seçerek karşılaştırma oluşturdum.
      - Zaman aralığı seçerek karşılaştırma oluşturamadım.
          - Zaman aralığı dolu.
      - Saha seçerek karşılaştırma oluşturdum.
      - Saha seçerek karşılaştırma oluşturamadım.
          - Saha kriterleri uygun değil, tekrar tercihlere bakacağım.
          - Ücret pahalı,tekrar tercihlere bakacağım.

- Yeni bir karşılaştırma oluşturamadım;
      - Üye değilim, üye olmalarak tekrar denedim.

## 4-)Eşleşme Sonuçları

- Bildirim geldi;
      - Bir takım benimle maç yapmak istiyor.
      - Bu takım için yorumlara bakacağım.
          - Yorumlar sonucunda kabul ettim.
          - Kabul etmedim.
      - Karşılaşmayı kabul ediyorum.
          - Rakip takıma bildirim gider.
      - Karşılaşmayı kabul etmiyorum.
          - Diğer rakip isteklerine bakılır.
          - Başka istek yoksa;
               - Rakip isteği beklenir ya da rakip arama kullanılabilir.

- Bildirim gelmedi;
     - Yeni bir karşılaşma isteği yok.
           - Rakip isteği beklenir ya da rakip arama kullanılabilir.

## 5-)Rakiplerin Yorumu

- Maç sonunda yorum atabilirim.
    - Fikirlerimi yazdım yolladım.
         - Puan girmemi istedi.
               - Puan girdim yolladım.
                    

- Maç zamanından önce yorum attım.
    -  Hata mesajı..

**Comment by umutbarangok** [comment]
deneme1
